import type { DnD5eRace, DnD5eClass, DnD5eBackground } from '../types'

export const DND5E_RACES: DnD5eRace[] = [
  {
    name: 'Human',
    description: 'Versatile and ambitious, humans are the most adaptable of the common races.',
    abilityScoreIncrease: { strength: 1, dexterity: 1, constitution: 1, intelligence: 1, wisdom: 1, charisma: 1 },
    size: 'Medium',
    speed: 30,
    traits: ['Extra Language', 'Extra Skill'],
    languages: ['Common'],
  },
  {
    name: 'Elf',
    description: 'Magical people of otherworldly grace, living in harmony with the natural world.',
    abilityScoreIncrease: { dexterity: 2 },
    size: 'Medium',
    speed: 30,
    traits: ['Darkvision', 'Keen Senses', 'Fey Ancestry', 'Trance'],
    languages: ['Common', 'Elvish'],
    proficiencies: ['Perception'],
  },
  {
    name: 'Dwarf',
    description: 'Bold and hardy, dwarves are known as skilled warriors, miners, and workers of stone and metal.',
    abilityScoreIncrease: { constitution: 2 },
    size: 'Medium',
    speed: 25,
    traits: ['Darkvision', 'Dwarven Resilience', 'Stonecunning'],
    languages: ['Common', 'Dwarvish'],
  },
  {
    name: 'Halfling',
    description: 'Small and practical, halflings are known for their resourcefulness and bravery.',
    abilityScoreIncrease: { dexterity: 2 },
    size: 'Small',
    speed: 25,
    traits: ['Lucky', 'Brave', 'Halfling Nimbleness'],
    languages: ['Common', 'Halfling'],
  },
  {
    name: 'Dragonborn',
    description: 'Born of dragons, as their name proclaims, dragonborn walk proudly through a world that greets them with fearful incomprehension.',
    abilityScoreIncrease: { strength: 2, charisma: 1 },
    size: 'Medium',
    speed: 30,
    traits: ['Draconic Ancestry', 'Breath Weapon', 'Damage Resistance'],
    languages: ['Common', 'Draconic'],
  },
  {
    name: 'Gnome',
    description: 'Small, energetic, and inquisitive, gnomes are known for their love of gems, jokes, and all things mechanical.',
    abilityScoreIncrease: { intelligence: 2 },
    size: 'Small',
    speed: 25,
    traits: ['Darkvision', 'Gnome Cunning'],
    languages: ['Common', 'Gnomish'],
  },
  {
    name: 'Half-Elf',
    description: 'Walking in two worlds but truly belonging to neither, half-elves combine what some say are the best qualities of their elf and human parents.',
    abilityScoreIncrease: { charisma: 2 },
    size: 'Medium',
    speed: 30,
    traits: ['Darkvision', 'Fey Ancestry', 'Two Skills'],
    languages: ['Common', 'Elvish'],
  },
  {
    name: 'Half-Orc',
    description: 'Whether united under the leadership of a mighty warlock or having fought to a standstill after years of conflict, orc and human tribes sometimes form alliances.',
    abilityScoreIncrease: { strength: 2, constitution: 1 },
    size: 'Medium',
    speed: 30,
    traits: ['Darkvision', 'Relentless Endurance', 'Savage Attacks'],
    languages: ['Common', 'Orc'],
  },
  {
    name: 'Tiefling',
    description: 'To be greeted with stares and whispers, to suffer violence and insult on the street, to see mistrust and fear in every eye.',
    abilityScoreIncrease: { intelligence: 1, charisma: 2 },
    size: 'Medium',
    speed: 30,
    traits: ['Darkvision', 'Hellish Resistance', 'Infernal Legacy'],
    languages: ['Common', 'Infernal'],
  },
]

export const DND5E_CLASSES: DnD5eClass[] = [
  {
    name: 'Fighter',
    description: 'Masters of martial combat, skilled with a variety of weapons and armor.',
    hitDie: 10,
    primaryAbility: ['Strength', 'Dexterity'],
    savingThrows: ['Strength', 'Constitution'],
    skills: ['Acrobatics', 'Animal Handling', 'Athletics', 'History', 'Insight', 'Intimidation', 'Perception', 'Survival'],
    equipment: ['Chain mail', 'Shield', 'Martial weapon', 'Light crossbow'],
    features: ['Fighting Style', 'Second Wind'],
  },
  {
    name: 'Wizard',
    description: 'Scholarly magic-users capable of manipulating the structures of reality.',
    hitDie: 6,
    primaryAbility: ['Intelligence'],
    savingThrows: ['Intelligence', 'Wisdom'],
    skills: ['Arcana', 'History', 'Insight', 'Investigation', 'Medicine', 'Religion'],
    equipment: ['Quarterstaff', 'Dagger', 'Spellbook', 'Scholars pack'],
    features: ['Spellcasting', 'Arcane Recovery'],
  },
  {
    name: 'Rogue',
    description: 'Scoundrels who use stealth and trickery to overcome obstacles.',
    hitDie: 8,
    primaryAbility: ['Dexterity'],
    savingThrows: ['Dexterity', 'Intelligence'],
    skills: ['Acrobatics', 'Athletics', 'Deception', 'Insight', 'Intimidation', 'Investigation', 'Perception', 'Performance', 'Persuasion', 'Sleight of Hand', 'Stealth'],
    equipment: ['Rapier', 'Shortbow', 'Leather armor', 'Thieves tools'],
    features: ['Expertise', 'Sneak Attack', 'Thieves Cant'],
  },
  {
    name: 'Cleric',
    description: 'Priestly champions who wield divine magic in service of a higher power.',
    hitDie: 8,
    primaryAbility: ['Wisdom'],
    savingThrows: ['Wisdom', 'Charisma'],
    skills: ['History', 'Insight', 'Medicine', 'Persuasion', 'Religion'],
    equipment: ['Scale mail', 'Shield', 'Mace', 'Light crossbow'],
    features: ['Spellcasting', 'Divine Domain'],
  },
  {
    name: 'Ranger',
    description: 'Warriors of the wilderness, skilled in tracking, survival, and combat.',
    hitDie: 10,
    primaryAbility: ['Dexterity', 'Wisdom'],
    savingThrows: ['Strength', 'Dexterity'],
    skills: ['Animal Handling', 'Athletics', 'Insight', 'Investigation', 'Nature', 'Perception', 'Stealth', 'Survival'],
    equipment: ['Scale mail', 'Longbow', 'Scimitar', 'Explorers pack'],
    features: ['Favored Enemy', 'Natural Explorer'],
  },
  {
    name: 'Paladin',
    description: 'Holy warriors bound to a sacred oath, wielding divine magic and martial prowess.',
    hitDie: 10,
    primaryAbility: ['Strength', 'Charisma'],
    savingThrows: ['Wisdom', 'Charisma'],
    skills: ['Athletics', 'Insight', 'Intimidation', 'Medicine', 'Persuasion', 'Religion'],
    equipment: ['Chain mail', 'Shield', 'Martial weapon', 'Javelins'],
    features: ['Divine Sense', 'Lay on Hands'],
  },
  {
    name: 'Barbarian',
    description: 'Fierce warriors of primitive background who can enter a battle rage.',
    hitDie: 12,
    primaryAbility: ['Strength'],
    savingThrows: ['Strength', 'Constitution'],
    skills: ['Animal Handling', 'Athletics', 'Intimidation', 'Nature', 'Perception', 'Survival'],
    equipment: ['Hide armor', 'Greataxe', 'Handaxe', 'Explorers pack'],
    features: ['Rage', 'Unarmored Defense'],
  },
  {
    name: 'Bard',
    description: 'Masters of song, speech, and the magic they contain.',
    hitDie: 8,
    primaryAbility: ['Charisma'],
    savingThrows: ['Dexterity', 'Charisma'],
    skills: ['Any three of your choice'],
    equipment: ['Leather armor', 'Rapier', 'Lute', 'Entertainers pack'],
    features: ['Spellcasting', 'Bardic Inspiration'],
  },
  {
    name: 'Druid',
    description: 'Priests of nature, wielding elemental forces and transformative magic.',
    hitDie: 8,
    primaryAbility: ['Wisdom'],
    savingThrows: ['Intelligence', 'Wisdom'],
    skills: ['Arcana', 'Animal Handling', 'Insight', 'Medicine', 'Nature', 'Perception', 'Religion', 'Survival'],
    equipment: ['Leather armor', 'Shield', 'Scimitar', 'Explorers pack'],
    features: ['Druidcraft', 'Wild Shape'],
  },
  {
    name: 'Monk',
    description: 'Masters of martial arts, harnessing inner power through discipline.',
    hitDie: 8,
    primaryAbility: ['Dexterity', 'Wisdom'],
    savingThrows: ['Strength', 'Dexterity'],
    skills: ['Acrobatics', 'Athletics', 'History', 'Insight', 'Religion', 'Stealth'],
    equipment: ['Simple weapon', 'Dart', 'Explorers pack'],
    features: ['Unarmored Defense', 'Martial Arts'],
  },
  {
    name: 'Sorcerer',
    description: 'Spellcasters who draw on inherent magic from a gift or bloodline.',
    hitDie: 6,
    primaryAbility: ['Charisma'],
    savingThrows: ['Constitution', 'Charisma'],
    skills: ['Arcana', 'Deception', 'Insight', 'Intimidation', 'Persuasion', 'Religion'],
    equipment: ['Light crossbow', 'Dagger', 'Explorers pack'],
    features: ['Spellcasting', 'Sorcerous Origin'],
  },
  {
    name: 'Warlock',
    description: 'Wielders of magic derived from a bargain with an extraplanar entity.',
    hitDie: 8,
    primaryAbility: ['Charisma'],
    savingThrows: ['Wisdom', 'Charisma'],
    skills: ['Arcana', 'Deception', 'History', 'Intimidation', 'Investigation', 'Nature', 'Religion'],
    equipment: ['Light crossbow', 'Simple weapon', 'Leather armor', 'Explorers pack'],
    features: ['Otherworldly Patron', 'Pact Magic'],
  },
]

export const DND5E_BACKGROUNDS: DnD5eBackground[] = [
  {
    name: 'Acolyte',
    description: 'You have spent your life in service to a temple, learning sacred rites and providing sacrifices.',
    skillProficiencies: ['Insight', 'Religion'],
    languages: 2,
    equipment: ['Holy symbol', 'Prayer book', 'Incense', 'Vestments'],
    feature: 'Shelter of the Faithful',
    personalityTraits: [
      'I idolize a particular hero of my faith.',
      'I can find common ground between the fiercest enemies.',
      'I see omens in every event and action.',
      'Nothing can shake my optimistic attitude.',
    ],
    ideals: [
      'Tradition. The ancient traditions must be preserved.',
      'Charity. I always try to help those in need.',
      'Change. We must help bring about the changes the gods are constantly working in the world.',
      'Power. I hope to one day rise to the top of my faiths religious hierarchy.',
    ],
    bonds: [
      'I would die to recover an ancient relic of my faith.',
      'I will someday get revenge on the corrupt temple hierarchy.',
      'I owe my life to the priest who took me in when my parents died.',
      'Everything I do is for the common people.',
    ],
    flaws: [
      'I judge others harshly, and myself even more severely.',
      'I put too much trust in those who wield power within my temples hierarchy.',
      'My piety sometimes leads me to blindly trust those that profess faith in my god.',
      'I am inflexible in my thinking.',
    ],
  },
  {
    name: 'Criminal',
    description: 'You are an experienced criminal with a history of breaking the law.',
    skillProficiencies: ['Deception', 'Stealth'],
    languages: 0,
    equipment: ['Crowbar', 'Dark common clothes', 'Belt pouch'],
    feature: 'Criminal Contact',
    personalityTraits: [
      'I always have a plan for what to do when things go wrong.',
      'I am always calm, no matter what the situation.',
      'The first thing I do in a new place is note the locations of everything valuable.',
      'I would rather make a new friend than a new enemy.',
    ],
    ideals: [
      'Honor. I dont steal from others in the trade.',
      'Freedom. Chains are meant to be broken.',
      'Charity. I steal from the wealthy so that I can help people in need.',
      'Greed. I will do whatever it takes to become wealthy.',
    ],
    bonds: [
      'Im trying to pay off an old debt I owe to a generous benefactor.',
      'My ill-gotten gains go to support my family.',
      'Something important was taken from me, and I aim to steal it back.',
      'I will become the greatest thief that ever lived.',
    ],
    flaws: [
      'When I see something valuable, I cant think about anything but how to steal it.',
      'When faced with a choice between money and my friends, I usually choose the money.',
      'If theres a plan, Ill forget it. If I dont forget it, Ill ignore it.',
      'I have a tell that reveals when Im lying.',
    ],
  },
  {
    name: 'Folk Hero',
    description: 'You come from a humble social rank, but you are destined for so much more.',
    skillProficiencies: ['Animal Handling', 'Survival'],
    languages: 0,
    equipment: ['Artisans tools', 'Shovel', 'Set of artisans clothes'],
    feature: 'Rustic Hospitality',
    personalityTraits: [
      'I judge people by their actions, not their words.',
      'If someone is in trouble, Im always ready to lend help.',
      'When I set my mind to something, I follow through no matter what gets in my way.',
      'I have a strong sense of fair play and always try to find the most equitable solution to arguments.',
    ],
    ideals: [
      'Respect. People deserve to be treated with dignity and respect.',
      'Fairness. No one should get preferential treatment before the law.',
      'Freedom. Tyrants must not be allowed to oppress the people.',
      'Might. If I become strong, I can take what I want—what I deserve.',
    ],
    bonds: [
      'I have a family, but I have no idea where they are.',
      'I worked the land, I love the land, and I will protect the land.',
      'A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.',
      'My tools are symbols of my past life, and I carry them so that I will never forget my roots.',
    ],
    flaws: [
      'The tyrant who rules my land will stop at nothing to see me killed.',
      'Im convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.',
      'The people who knew me when I was young know my shameful secret, so I can never go home again.',
      'I have a weakness for the vices of the city, especially hard drink.',
    ],
  },
  {
    name: 'Noble',
    description: 'You understand wealth, power, and privilege.',
    skillProficiencies: ['History', 'Persuasion'],
    languages: 1,
    equipment: ['Signet ring', 'Scroll of pedigree', 'Fine clothes'],
    feature: 'Position of Privilege',
    personalityTraits: [
      'My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.',
      'The common folk love me for my kindness and generosity.',
      'No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.',
      'I take great pains to always look my best and follow the latest fashions.',
    ],
    ideals: [
      'Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity.',
      'Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine.',
      'Independence. I must prove that I can handle myself without the coddling of my family.',
      'Power. If I can attain more power, no one will tell me what to do.',
    ],
    bonds: [
      'I will face any challenge to win the approval of my family.',
      'My house's alliance with another noble family must be sustained at all costs.',
      'Nothing is more important than the other members of my family.',
      'I am in love with the heir of a family that my family despises.',
    ],
    flaws: [
      'I secretly believe that everyone is beneath me.',
      'I hide a truly scandalous secret that could ruin my family forever.',
      'I too often hear veiled insults and threats in every word addressed to me, and Im quick to anger.',
      'I have an insatiable desire for carnal pleasures.',
    ],
  },
  {
    name: 'Sage',
    description: 'You spent years learning the lore of the multiverse.',
    skillProficiencies: ['Arcana', 'History'],
    languages: 2,
    equipment: ['Bottle of black ink', 'Quill', 'Small knife', 'Letter from colleague'],
    feature: 'Researcher',
    personalityTraits: [
      'I use polysyllabic words that convey the impression of great erudition.',
      'Ive read every book in the worlds greatest libraries—or I like to boast that I have.',
      'Im used to helping out those who arent as smart as I am, and I patiently explain anything and everything to others.',
      'Theres nothing I like more than a good mystery.',
    ],
    ideals: [
      'Knowledge. The path to power and self-improvement is through knowledge.',
      'Beauty. What is beautiful points us beyond itself toward what is true.',
      'Logic. Emotions must not cloud our logical thinking.',
      'No Limits. Nothing should fetter the infinite possibility inherent in all existence.',
    ],
    bonds: [
      'It is my duty to protect my students.',
      'I have an ancient text that holds terrible secrets that must not fall into the wrong hands.',
      'I work to preserve a library, university, scriptorium, or monastery.',
      'My lifes work is a series of tomes related to a specific field of lore.',
    ],
    flaws: [
      'I am easily distracted by the promise of information.',
      'Most people scream and run when they see a demon. I stop and take notes on its anatomy.',
      'Unlocking an ancient mystery is worth the price of a civilization.',
      'I overlook obvious solutions in favor of complicated ones.',
    ],
  },
  {
    name: 'Soldier',
    description: 'War has been your life for as long as you care to remember.',
    skillProficiencies: ['Athletics', 'Intimidation'],
    languages: 0,
    equipment: ['Insignia of rank', 'Trophy from fallen enemy', 'Deck of cards', 'Common clothes'],
    feature: 'Military Rank',
    personalityTraits: [
      'I can stare down a hell hound without flinching.',
      'I enjoy being strong and like breaking things.',
      'I have a crude sense of humor.',
      'I face problems head-on. A simple, direct solution is the best path to success.',
    ],
    ideals: [
      'Greater Good. Our lot is to lay down our lives in defense of others.',
      'Responsibility. I do what I must and obey just authority.',
      'Independence. When people follow orders blindly, they embrace a kind of tyranny.',
      'Might. In life as in war, the stronger force wins.',
    ],
    bonds: [
      'I would still lay down my life for the people I served with.',
      'Someone saved my life on the battlefield. To this day, I will never leave a friend behind.',
      'My honor is my life.',
      'Ill never forget the crushing defeat my company suffered or the enemies who dealt it.',
    ],
    flaws: [
      'The monstrous enemy we faced in battle still leaves me quivering with fear.',
      'I have little respect for anyone who is not a proven warrior.',
      'I made a terrible mistake in battle that cost many lives—and I would do anything to keep that mistake secret.',
      'My hatred of my enemies is blind and unreasoning.',
    ],
  },
]

export const ALIGNMENTS = [
  'Lawful Good',
  'Neutral Good',
  'Chaotic Good',
  'Lawful Neutral',
  'True Neutral',
  'Chaotic Neutral',
  'Lawful Evil',
  'Neutral Evil',
  'Chaotic Evil',
]

export const ABILITY_SCORES = [
  'strength',
  'dexterity',
  'constitution',
  'intelligence',
  'wisdom',
  'charisma',
] as const

export const SKILLS = [
  'Acrobatics',
  'Animal Handling',
  'Arcana',
  'Athletics',
  'Deception',
  'History',
  'Insight',
  'Intimidation',
  'Investigation',
  'Medicine',
  'Nature',
  'Perception',
  'Performance',
  'Persuasion',
  'Religion',
  'Sleight of Hand',
  'Stealth',
  'Survival',
]

